### ISSUE TITLE
JSON parse error

### ISSUE THREAD

**Issue by lcgerke** [jenkinsci/caliper-ci-plugin#3]
Hey, sorry I haven't debugged this more, but...

The plugin has been barfing for me in the deserialization of results files.  eg (from jenkins main log)

Could not parse file as JSON, skipping: com.lcgerke.lcgutil.caliperexample.ListIterationBenchmark.2014-05-01T21:02:48Z.json
com.google.gson.JsonParseException: Expecting array but found object: null@null
    at com.google.gson.JsonArrayDeserializationVisitor.startVisitingObject(JsonArrayDeserializationVisitor.java:89)
    at com.google.gson.ObjectNavigator.accept(ObjectNavigator.java:119)
    at com.google.gson.JsonDeserializationContextDefault.fromJsonArray(JsonDeserializationContextDefault.java:67)
    at com.google.gson.JsonDeserializationContextDefault.deserialize(JsonDeserializationContextDefault.java:52)
    at com.google.gson.Gson.fromJson(Gson.java:551)
    at com.google.gson.Gson.fromJson(Gson.java:498)
    at com.google.gson.Gson.fromJson(Gson.java:467)
    at com.google.gson.Gson.fromJson(Gson.java:417)
    at com.google.gson.Gson.fromJson(Gson.java:389)
    at com.brianfromoregon.CaliperResultsRecorder.perform(CaliperResultsRecorder.java:72)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:740)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:710)
    at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1036)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:659)
    at hudson.model.Run.execute(Run.java:1728)
    at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:525)
    at hudson.model.ResourceController.execute(ResourceController.java:88)
    at hudson.model.Executor.run(Executor.java:231)

....

I tried to clone the project to verify that parsing was working in tests, but in an unmodified clone, i got the following on "mvn test" (linux, maven3).  

May 01, 2014 7:27:44 PM com.brianfromoregon.CaliperResultsRecorder perform
WARNING: Could not parse file as JSON, skipping:
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' near {"run";{"benchmarkName";"ex
        at com.google.gson.Streams.parse(Streams.java:51)
        at com.google.gson.Gson.fromJson(Gson.java:497)
        at com.google.gson.Gson.fromJson(Gson.java:467)
        at com.google.gson.Gson.fromJson(Gson.java:417)
        at com.google.gson.Gson.fromJson(Gson.java:389)
        at com.brianfromoregon.CaliperResultsRecorder.perform(CaliperResultsRecorder.java:72)
        at com.brianfromoregon.TestCaliperResultsRecorder.bad_results_are_skipped(TestCaliperResultsRecorder.java:78)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
        at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
        at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:119)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:101)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
        at com.sun.proxy.$Proxy0.invoke(Unknown Source)
        at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:150)
        at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:91)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)
Caused by: com.google.gson.stream.MalformedJsonException: Expected ':' near {"run";{"benchmarkName";"ex
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1111)
        at com.google.gson.stream.JsonReader.objectValue(JsonReader.java:778)
        at com.google.gson.stream.JsonReader.quickPeek(JsonReader.java:377)
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:340)
        at com.google.gson.Streams.parseRecursive(Streams.java:60)
        at com.google.gson.Streams.parseRecursive(Streams.java:83)
        at com.google.gson.Streams.parse(Streams.java:40)
        ... 36 more

It doesn't look exactly the same, but I'm wondering if there might be some global JSON parsing issue.  Any thoughts, before I try to start debugging it myself?

Thanks for your hard work.

**Comment by brianfromoregon** [comment]
Which version of caliper are you using? caliper-ci uses an ooooooold version of caliper for its json schema so if you are using something recent it probably won't work. I'm not working on caliper-ci these days, but I'd be happy to merge a pull request and release a new version if you want to make the update.

**Comment by lcgerke** [comment]
alright.  will see if i can get it working....
thanks.
